server:
  port: 9999
spring:
  application:
    name: springcloud-zuul
#eureka配置，配置服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept #eureka注册中心的服务提供者的路由名称
    mydept.path: /mydept/** #将eureka注册中心的服务提供方的路由改为自定义路由
  ignored-services: "*" #忽略隐藏全部服务名称
  prefix: /izuul