server:
  port: 8001
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/clouddb?serverTimezone=UTC&characterEncoding=UTF-8
mybatis:
  mapper-locations: classpath:/mapper/*.xml
#eureka配置，配置服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
info:
  app.name: springcloud-provider
  company.name: com.siven